#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

[ -n "$CI" ] && exit 0

# Check the file name
# ! ls-lint cannot be used normally in mac pro of M1 system.
pnpm lint:ls-lint

# Format and submit code according to lintstagedrc.js configuration
pnpm lint:lint-staged
pnpm lint:pretty
